### PR TITLE
Fixes #320

### LINKED ISSUE #320: Fatal error: Cannot read property 'length' of null
I'm getting `Fatal error: Cannot read property 'length' of null` on images that I've optimized with [TinyPNG](https://tinypng.com/) (but aren't corrupt). Here's an example image:

myimage

`ImageMagick's` `identify` outputs `myImage.png PNG 29x29 29x29+0+0 8-bit sRGB 28c 409B 0.000u 0:00.000` so the image appears to be valid, but `imagemin` has trouble with it.

I'm using `grunt-contrib-imagemin v0.9.4`.

Thanks!

### PR DESCRIPTION
**Pull request by vivekkodira1**
Sometimes data[0].contents is returned as null. This adds a null check to avoid a runtime exception

### CODE REVIEW

**Comment by vivekkodira1** [comment]
Are there any issues with this PR? I'd be glad to fix them.

File: tasks/imagemin.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ module.exports = function (grunt) {
                     }
 
                     var origSize = stats.size;
-                    var diffSize = origSize - data[0].contents.length;
+                    var diffSize = origSize - ( ( data[0].contents && data[0].contents.length ) || 0 );
```
Comment (kevva) [inline tasks/imagemin.js]: `var diffSize = origSize - ((data[0].contents && data[0].contents.length) || 0);`

Comment (vivekkodira1) [inline tasks/imagemin.js]: Didn't understand this note @kevva

Comment (kevva) [inline tasks/imagemin.js]: Remove the spaces inside the parentheses.
